# Generated by Django 5.2.12 on 2026-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('travel_date', models.DateField()),
                ('trip_type', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
