# Generated by Django 5.2.12 on 2026-03-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0003_blogcategory_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('btn1_text', models.CharField(blank=True, max_length=100)),
                ('btn2_text', models.CharField(blank=True, max_length=100)),
                ('background_media', models.FileField(blank=True, null=True, upload_to='hero/')),
            ],
        ),
    ]
