# Generated by Django 5.2.12 on 2026-03-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0004_herosection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='background_media',
        ),
        migrations.CreateModel(
            name='HeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='GovoloApp.herosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
