# Generated by Django 5.2.12 on 2026-03-31 06:49

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0006_tourcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('main_image', models.ImageField(upload_to='destinations/')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. used in navbar, highlights, etc.', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_top', models.BooleanField(default=False)),
                ('show_in_navbar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Asia, Europe, etc.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. International, Domestic', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-star', max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='GovoloApp.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destination_gallery/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='GovoloApp.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='GovoloApp.destination')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='GovoloApp.destinationregion'),
        ),
        migrations.AddField(
            model_name='destinationregion',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='GovoloApp.destinationtype'),
        ),
    ]
