# Generated by Django 5.2.12 on 2026-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0007_destination_destinationregion_destinationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='video',
            field=models.FileField(blank=True, help_text='This video will be used in the destination detail hero section', null=True, upload_to='destinations/videos/'),
        ),
    ]
