# Generated by Django 5.2.12 on 2026-04-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0008_destination_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTripInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_type', models.CharField(blank=True, choices=[('Solo', 'Solo'), ('Couple', 'Couple'), ('Family', 'Family'), ('Friends', 'Friends')], max_length=20)),
                ('travelers_count', models.PositiveIntegerField(default=1)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('duration_days', models.PositiveIntegerField(default=5)),
                ('departure_airport', models.CharField(blank=True, max_length=100)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('daily_plan', models.JSONField(blank=True, default=dict)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trip Inquiry',
                'verbose_name_plural': 'Trip Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
