# Generated by Django 5.2.12 on 2026-04-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0010_tourday_alter_customtripinquiry_options_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
