# Generated by Django 5.2.12 on 2026-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0011_package_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageactivity',
            name='day',
            field=models.IntegerField(help_text='e.g. 1, 2'),
        ),
    ]
