# Generated by Django 5.2.12 on 2026-04-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0012_alter_packageactivity_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageactivity',
            name='day',
            field=models.IntegerField(help_text="e.g. 'Day 1', 'Day 2'", max_length=50),
        ),
    ]
