# Generated by Django 5.2.12 on 2026-04-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0014_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('travel_date', models.DateField()),
                ('trip_type', models.CharField(choices=[('Solo', 'Solo'), ('Couple', 'Couple'), ('Family', 'Family'), ('Group', 'Group')], max_length=20)),
                ('budget', models.CharField(choices=[('Economic', 'Economic'), ('Comfort', 'Comfort'), ('Premium', 'Premium'), ('Luxury', 'Luxury')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='GovoloApp.package')),
            ],
            options={
                'verbose_name': 'Package Inquiry',
                'verbose_name_plural': 'Package Inquiries',
            },
        ),
    ]
