# Generated by Django 5.2.12 on 2026-04-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0015_packageinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationtype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
