# Generated by Django 5.2.12 on 2026-04-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0016_destinationtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationtype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
