# Generated by Django 5.2.12 on 2026-04-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0017_alter_destinationtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='GovoloApp.destinationtype'),
        ),
    ]
