# Generated by Django 5.2.12 on 2026-04-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0018_destination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='GovoloApp.destinationregion'),
        ),
    ]
