# Generated by Django 5.2.12 on 2026-04-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0019_alter_destination_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationitinerary',
            name='description',
        ),
    ]
