# Generated by Django 5.2.12 on 2026-04-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0020_remove_destinationitinerary_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationitinerary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
