# Generated by Django 5.2.12 on 2026-04-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GovoloApp', '0021_destinationitinerary_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationitinerary',
            name='description',
        ),
    ]
